### ISSUE TITLE
Is this module still supported?

### ISSUE THREAD

**Issue by XMol** [desyops/puppet-afs#4]
Hello,

we've been using this module in some very niche situations so far. Nevertheless, we're currently migrating to Puppet 5 and are wondering whether this module still is maintained at all. Considering that the last commit was about 5 years ago, I'm pretty sure that isn't the case.

Best regards,  
Xavier.

**Comment by stdietrich** [comment]
Hello Xavier,

well, not really. We had always a local version in our VCS due to site specific changes (scripts, cronjobs etc.).
Those changes aside, it does not differ that much from this version except for CentOS 7 support by expanding params.pp to use the RPMs from Scientific Linux 7.
The module still runs fine with Puppet 5, as we are already on Puppet 5.

As we will probably not invest a lot of time any more in this module and the conflicting deployment options on CentOS 7 (openafs.org packages vs CentOS SIG vs. Scientific Linux RPMs), this repo will be archived.
Feel free to fork and continue!

Regards,
Stefan

**Comment by XMol** [comment]
Thanks Stefan,

our use case for AFS is very limited, so we probably will then simply stop deploying it all together.

Ciao,
Xavier.
